changed app file
Shrashi/pink-tulips pull request #1
Opened 2022-03-23 18:55 UTC by Shrashi

2022-03-23 19:02 UTC, SwarnTyagi requested changes
Please do changes

2022-03-28 09:07 UTC, SwarnTyagi commented on frontend/src/App.js
> +    primary: "#ffffff",
it can be #fff, if only white is required

2022-03-28 09:31 UTC, SwarnTyagi requested changes
Please check the comments minutely and ask me if something required from my end

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/App.js
> +  };
remove it, if not in use

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/App.js
> +            <Route path="/signUp" exact={true} element={<SignUp />} />
instead of **exact={true}**, you can write **exact**only. React by default treat empty attributes as boolean true

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Button/button.css
> +}
please remove, if not in use

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Button/button.css
> +}
add hover element using styled component and using primary and secondary colors

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Button/button.css
> +}
Please check these also, if not required, then remove

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Field/SearchField.js
> +  };
Local state can be removed, make it Controlled Component, 
pass callback and value as a prop

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Field/SearchField.js
> +    </div>
Make it styled component

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Field/TextField.js
> +    <div>
give some className, don't keep empty div in return. Or if it is only for wrapping elements, try to use Fragment

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Field/TextField.js
> +        onChange={onChangeField}
make wrapper function for onChange in the component

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/Form.js
> +import styled from "styled-components";
libraries should always on the top, then project files

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/Form.js
> +    var re = /^(?=.*\d)(?=.*[!@#$%^&*])(?=.*[a-z])(?=.*[A-Z]).{8,}$/;
make utils and constant file for reusable text or regex

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/Form.js
> +      console.log("Details Submitted");
remove console

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/Form.js
> +      alert("Password must contain special character,alphanumeric characters.");
remove alert

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/Form.js
> +  const onFieldChange = (e) => {
instead of e, you can have name, value from wrapper function

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/Form.js
> +  console.log("Form state is", formState);
remove console from every place

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/FormRules.js
> +export const FormRules = [
Form Rules is not a Component, make it camelCase

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/Form.js
> +  const onFormSubmit = () => {
it should be wrapper function, and onFormSubmit should come from prop

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/FormItems.js
> +export const FormItems = [
use camelCase

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/FormItems.js
> +    id: "name-sign-up",
id not required in config, remove from every place

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/FormItems.js
> +    type: "text",
no need to mention type:text, 
make it text by default in Form Component, if **type** is not coming in config object

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/useFormErrors.js
> +  };
Move these methods in utils, then import

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Form/useFormErrors.js
> +      require[ele.fieldName] = reqStr;
instead of using ele. again n again, destructure ele

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Header/Header.js
> +import styled from "styled-components";
rearrange libraries in order

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Header/Header.js
> +  // position: fixed;
remove commented code

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Header/Header.js
> +    console.log("Button is clicked");
remove console

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Header/Header.js
> +      onIcon && onIcon(ele.title);
destructure ele

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Header/Header.js
> +      </div> */}
remove if not in use

2022-03-28 09:31 UTC, SwarnTyagi commented on frontend/src/components/Header/MenuItems.js
> +export const MenuItems = [
use camelCase

2022-03-29 06:46 UTC, Shrashi commented on frontend/src/components/Form/FormItems.js
> +    id: "name-sign-up",
I felt it is required for unique identification, so I am not removing it for now.

2022-03-29 08:10 UTC, merged